# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticetype',
            name='delay',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Delay between Notices'),
        ),
    ]
